theme: jekyll-theme-cayman

title: [Catalyst Open Banking]
description: [The Catalyst Bank uses Open Banking Concepts in North America to support the Digital Transformation of the Financial Services Industry]